name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set git identity
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email 'the-hackathon@users.noreply.github.com'

      - name: Set git remote
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/The-Hackathon/thehackathon.dev.git

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v3-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            v3-${{ runner.os }}

      - name: Install dependencies
        run: yarn install

      - name: Clean GH Pages
        run: node_modules/.bin/gh-pages-clean

      - name: Deploy
        run: npm run deploy
